name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore
#    - name: Test
#      run: |
#        cd src
#        dotnet test --no-restore --verbosity normal
    - name: Build solution and generate NuGet package
      run: |  
        cd src/Nager.HetznerDns
        dotnet pack --configuration Release --output $GITHUB_WORKSPACE/out

    - name: Push generated package NuGet
      run: dotnet nuget push $GITHUB_WORKSPACE/out/*.nupkg --source https://www.nuget.org/api/v2/package --api-key ${{secrets.NUGET_TOKEN}} --skip-duplicate --no-symbols
